name: 'ticket-collector'
description: 'Collects ticket ids'
inputs:
  owner:
    description: 'Owner of the repository'
    required: true
  repository:
    description: 'Name of the repository'
    required: true
  pr-id:
    description: 'ID of PR'
    required: true
  output-file:
    description: 'File in which we should write the list of tickets'
    required: true
    #default: ''
#  jira-tickets:
#    description: 'comma-separated list of JIRA ticket IDs'
#    required: true
outputs: {}
runs:
  using: 'node16'
  main: 'dist/index.js'
