name: 'ticket-collector'
description: 'Collects ticket ids'
inputs:
  owner:
    description: 'Owner of the repository'
    required: true
  repository:
    description: 'Name of the repository'
    required: true
  branch:
    description: 'The branch of the commit'
    required: true
  commit-sha:
    description: 'SHA of the commit'
    required: true
  parent-sha:
    description: 'SHA of the parent commit'
    required: true
  tag:
    description: 'Tag if applicable'
    required: false
  tickets:
    description: 'The tickets related to the commit'
    required: false
  created-at:
    description: 'The creation time of the commit'
    required: true
  aws-credentials:
    description: 'The AWS credentials used to put the commit into DynamoDB'
    required: true
  aws-region:
    description: 'The AWS region of the DynamoDB table'
    required: true
  dynamodb-tablename:
    description: 'The DynamoDB table name'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'