name: 'ticket-collector'
description: 'Collects ticket ids'
inputs:
  owner:
    description: 'Owner of the repository'
    required: true
  repository:
    description: 'Name of the repository'
    required: true
  override-repository:
    description: 'Override of the repository name'
    required: false
  ref-name:
    description: "Ref name"
    required: true
  ref-type:
    description: "Type of ref (such as branch or tag)"
    required: true
  ref-base:
    description: "Base ref (such as refs/heads/branchName)"
    required: false
  new-sha:
    description: 'SHA of the commit'
    required: true
  previous-sha:
    description: 'SHA of the parent commit'
    required: true
  commits:
    description: "The list of commits from the event, if applicable"
    required: false
  dynamodb-tablename:
    description: 'The DynamoDB table name'
    required: true
  jira-host:
    description: 'Domain name of the Jira Cloud server (Needed if you want to verify ticket list against Jira)'
    required: true
  jira-proxy:
    description: 'Proxy Domain name of the Jira Cloud server ( use for caching of search queries )'
    required: false
  jira-username:
    description: 'Jira username (Needed if you want to verify ticket list against Jira)'
    required: true
  jira-token:
    description: 'Jira token or password (Needed if you want to verify ticket list against Jira)'
    required: true
  gh-token:
    description: 'Github token with permission to query the PR and list commits'
    required: true
  git-search-base-url:
    description: 'Proxy URL for git search api'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'