name: Ticket store on push

on:
  workflow_call:
    inputs:
      override-repo-name:
        description: "Override of the repository name for when the repo name doesn't match the deployment name"
        required: false
        type: string

jobs:
  store-pushed-tickets:
    name: ticket store
    runs-on: ubuntu-latest
    steps:
      - name : machine echo github
        env : { CONTENT : "${{ toJson(github) }}" }
        run : "echo $CONTENT"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TICKET_COLLECTOR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TICKET_COLLECTOR_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: store valid tickets
        id: store
        uses: vimond/actions/ticket-storer@9dc6f7b9e472d6b7f500cdbd6320b18aac15d8ba
        with:
          owner: ${{ github.repository_owner }}
          repository: ${{ github.event.repository.name }}
          override-repository: ${{ inputs.override-repo-name }}
          ref-name: ${{ github.ref_name }}
          ref-type: ${{ github.ref_type }}
          ref-base: ${{ github.event.base_ref }}
          previous-sha: ${{ github.event.before }}
          new-sha: ${{ github.event.after }}
          commits: "${{ toJson(github.event.commits) }}"

          dynamodb-tablename: 'eu-north-1-internal-commit-tickets'

          jira-host: 'vimond-ng.atlassian.net'
          jira-username: ${{ secrets.JIRA_USERNAME }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-proxy: ${{ secrets.JIRA_PROXY_DOMAIN }}

          gh-token: ${{ secrets.ACTIONS_GITHUB_API_TOKEN }}
          git-search-base-url: ${{ secrets.GH_PROXY_DOMAIN }}