# This is a basic workflow to help you get started with Actions

name: Pull Request Validation

# Controls when the workflow will run
on:
  #  # Triggers the workflow on push or pull request events but only for the main branch
  #  pull_request:
  #    types: ['opened', 'edited', 'reopened', 'synchronize']
  ##    branches: [ main ]

  # Allows you to run this workflow from other workflows
  workflow_call:
    inputs:
      override-repo-name:
        description: "Override of the repository name for when the repo name doesn't match the deployment name"
        required: false
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
env:
  PR_ID: "${{ github.event.number }}"
jobs:
  pr-lint:
    name: ticket check
    runs-on: ubuntu-latest

    steps:
      - name : machine echo github
        env : { CONTENT : "${{ toJson(github) }}" }
        run : "echo $CONTENT"
      - name: show pr id (via shell)
        run: "echo PR ID: $PR_ID"
      - name: show or id (via context)
        run: "echo ${{ env.PR_ID }}"
      - name: collect tickets
        id: collect
        uses: vimond/actions/ticket-collector@0.0.1
        with:
          owner: ${{ github.repository_owner }}
          repository: ${{ github.event.repository.name }}
          pr-id: ${{ env.PR_ID }}
          output-file: './tickets.json'
          gh-token: ${{ secrets.ACTIONS_GITHUB_API_TOKEN }}
          git-search-base-url: ${{ secrets.GH_PROXY_DOMAIN }}
          jira-host: 'vimond-ng.atlassian.net'
          jira-username: ${{ secrets.JIRA_USERNAME }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-proxy: ${{ secrets.JIRA_PROXY_DOMAIN }}
      - name: Print the list of ticket
        run: echo "${{ steps.collect.outputs.tickets }}" | base64 -d
      - name: Update PR
        uses: vimond/actions/pr-update-ticket-list@0.0.1
        with:
          pr-id: ${{ env.PR_ID }}
          tickets: ${{ steps.collect.outputs.tickets }}
          gh-token: ${{ secrets.ACTIONS_GITHUB_API_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3.0.0
        with:
          aws-access-key-id: ${{ secrets.TICKET_COLLECTOR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TICKET_COLLECTOR_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Store tickets
        uses: vimond/actions/ticket-storer-pr@0.0.1
        with:
          owner: ${{ github.repository_owner }}
          repository: ${{ github.event.repository.name }}
          override-repository: ${{ inputs.override-repo-name }}
          pr-id: ${{ env.PR_ID }}
          tickets: ${{ steps.collect.outputs.tickets }}
          dynamodb-tablename: 'eu-north-1-internal-commit-tickets'

